### ISSUE TITLE
请问 train.py 中 model = PPO("MultiInputPolicy", env, policy_kwargs=policy_kwargs, verbose=1, 为什么报错 TypeError: 'module' object is not callable ，还有 test.py 中的model.zip 在哪？

### ISSUE THREAD

**Issue by Caiyishuai** [Necolizer/RM-PRT#3]
Traceback (most recent call last):
  File "E:\Program Files\JetBrains\PyCharm 2023.2.1\plugins\python\helpers\pydev\pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\Program Files\JetBrains\PyCharm 2023.2.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\AAAAA_EI_LLM\RM-PRT\train.py", line 143, in <module>
    model = PPO("MultiInputPolicy", env, policy_kwargs=policy_kwargs, verbose=1,
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\stable_baselines3\ppo\ppo.py", line 164, in __init__
    self._setup_model()
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\stable_baselines3\ppo\ppo.py", line 167, in _setup_model
    super()._setup_model()
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 123, in _setup_model
    self.policy = self.policy_class(  # type: ignore[assignment]
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\stable_baselines3\common\policies.py", line 853, in __init__
    super().__init__(
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\stable_baselines3\common\policies.py", line 481, in __init__
    self.features_extractor = self.make_features_extractor()
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\stable_baselines3\common\policies.py", line 120, in make_features_extractor
    return self.features_extractor_class(self.observation_space, **self.features_extractor_kwargs)
TypeError: 'module' object is not callable

**Comment by Caiyishuai** [comment]
Traceback (most recent call last):
  File "D:\AAAAA_EI_LLM\RM-PRT\train.py", line 168, in <module>
    model.learn(total_timesteps=10, callback=[checkpoint_callback, eval_callback])
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\stable_baselines3\ppo\ppo.py", line 308, in learn
    return super().learn(
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 259, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 169, in collect_rollouts
    actions, values, log_probs = self.policy(obs_tensor)
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\stable_baselines3\common\policies.py", line 617, in forward
    features = self.extract_features(obs)
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\stable_baselines3\common\policies.py", line 640, in extract_features
    return super().extract_features(obs, self.features_extractor)
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\stable_baselines3\common\policies.py", line 131, in extract_features
    return features_extractor(preprocessed_obs)
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Users\caiyi\anaconda3\envs\RoboWaiter\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\AAAAA_EI_LLM\RM-PRT\bcz\Extractor.py", line 111, in forward
    instructions.append(self.instructions[index])
KeyError: 10000040
